/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gadavis' at '10/3/14 7:16 PM' with Gradle 2.1
 *
 * @author gadavis, @date 10/3/14 7:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
